### ISSUE TITLE
Switch code pool

### ISSUE THREAD

**Issue by manuelcanepa-santex** [nevvermind/storm-mage-wizards#1]
Add the option to change between local and community when create a new module

**Comment by nevvermind** [comment]
@manuelcanepa-santex - there is no "create new module". What are you saying?

**Comment by manuelcanepa-santex** [comment]
Im sorry, i think that this issue tracker was for Mage Wizard for Netbeans.

**Comment by adragus-inviqa** [comment]
Yeah, though so. :) No worries.
